# Generated by Django 4.1 on 2023-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.CharField(max_length=500, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='tax_regime',
            field=models.CharField(max_length=500, null=True, verbose_name='Régimen fiscal'),
        ),
    ]
