# Generated by Django 4.1 on 2023-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0003_alter_bankaccount_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='interbank_key',
            field=models.BigIntegerField(null=True, verbose_name='Clave interbancaria'),
        ),
    ]
