# Generated by Django 4.1 on 2023-01-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0004_alter_bankaccount_interbank_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositcontrol',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bankaccount'),
        ),
        migrations.AddField(
            model_name='depositcontrol',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Importe'),
        ),
        migrations.AddField(
            model_name='depositcontrol',
            name='beneficiary',
            field=models.CharField(max_length=200, null=True, verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='depositcontrol',
            name='concept',
            field=models.CharField(max_length=200, null=True, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='depositcontrol',
            name='date',
            field=models.DateField(max_length=50, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='depositcontrol',
            name='invoice',
            field=models.IntegerField(null=True, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='depositcontrol',
            name='reference',
            field=models.BigIntegerField(null=True, verbose_name='Referencia bancaria'),
        ),
        migrations.AlterField(
            model_name='billedincome',
            name='bank_deposits',
            field=models.BigIntegerField(null=True, verbose_name='Depositos bancarios'),
        ),
        migrations.AlterField(
            model_name='billedincome',
            name='bank_reference',
            field=models.BigIntegerField(null=True, verbose_name='Referencia bancaria'),
        ),
    ]
