# Generated by Django 4.1 on 2023-01-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0005_depositcontrol_account_depositcontrol_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedincome',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer'),
        ),
        migrations.AddField(
            model_name='company',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='bankaccountscustomer',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='bankaccountscustomer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer'),
        ),
        migrations.AlterField(
            model_name='billedincome',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.company'),
        ),
        migrations.AlterField(
            model_name='billedincome',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.mainproduct'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='auxiliary_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary', to='systemERP.employee', verbose_name='Auxiliar de ventas'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='qa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA', to='systemERP.employee', verbose_name='Control de calidad'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='storekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storekeeper', to='systemERP.employee', verbose_name='Almacenista'),
        ),
        migrations.AlterField(
            model_name='doubledays',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='driversalary',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='extrahours',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='fileproducer',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.producer'),
        ),
        migrations.AlterField(
            model_name='filequotation',
            name='requisition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.requisition'),
        ),
        migrations.AlterField(
            model_name='fileunit',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.unit'),
        ),
        migrations.AlterField(
            model_name='gasoline',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.unit'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bankaccount'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.parcel'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='loanschargers',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='loansdrivers',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='outputproduct',
            name='presentation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.presentation'),
        ),
        migrations.AlterField(
            model_name='outputproduct',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.productw'),
        ),
        migrations.AlterField(
            model_name='paymentorderproducer',
            name='authorize_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutorizaOrdenPago_proveedor', to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='paymentorderproducer',
            name='generate_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GeneraOrdenPago_proveedor', to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='paymentorderproducer',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.producer', verbose_name='Productor'),
        ),
        migrations.AlterField(
            model_name='paymentorderproducer',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.segalmexreception', verbose_name='No. Boleta'),
        ),
        migrations.AlterField(
            model_name='paymentproducer',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bankaccount', verbose_name='Cuenta de banco'),
        ),
        migrations.AlterField(
            model_name='paymentproducer',
            name='pay_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.paymentorderproducer', verbose_name='Orden de Pago'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bankaccount'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.company'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.department'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='productquotation',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.presentation'),
        ),
        migrations.AlterField(
            model_name='productquotation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.productw'),
        ),
        migrations.AlterField(
            model_name='productwpresentation',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.presentation'),
        ),
        migrations.AlterField(
            model_name='productwpresentation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.productw'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='authorizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutorizaCotizacion', to='systemERP.employee', verbose_name='Autoriza'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='generator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GeneraCotizacion', to='systemERP.employee', verbose_name='Genera'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.department'),
        ),
        migrations.AlterField(
            model_name='rowoutputreview',
            name='bigbags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_presentation_bigbags', to='systemERP.presentation', verbose_name='Presentación de producto'),
        ),
        migrations.AlterField(
            model_name='rowoutputreview',
            name='packages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_presentation_packages', to='systemERP.presentation', verbose_name='Presentación de producto'),
        ),
        migrations.AlterField(
            model_name='rowoutputreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.productw', verbose_name='Producto de Almacen'),
        ),
        migrations.AlterField(
            model_name='rowticketreview',
            name='bigbags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_presentation_bigbags', to='systemERP.presentation', verbose_name='Presentación de producto'),
        ),
        migrations.AlterField(
            model_name='rowticketreview',
            name='packages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_presentation_packages', to='systemERP.presentation', verbose_name='Presentación de producto'),
        ),
        migrations.AlterField(
            model_name='rowticketreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.productw', verbose_name='Producto de Almacen'),
        ),
        migrations.AlterField(
            model_name='segalmexparcel',
            name='cycleoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CicloOI', to='systemERP.parcel'),
        ),
        migrations.AlterField(
            model_name='segalmexparcel',
            name='cyclepv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CicloPV', to='systemERP.parcel'),
        ),
        migrations.AlterField(
            model_name='segalmexparcel',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.society'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chofer', to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.location', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.unit', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.producer', verbose_name='Productor'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recibio', to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.variety', verbose_name='variedad'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicita', to='systemERP.employee', verbose_name='Solicita'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='authorizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoriza', to='systemERP.employee', verbose_name='Autoriza'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.provider', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='requisition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.requisition', verbose_name='Id Requisition'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='verify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifica', to='systemERP.employee', verbose_name='Verifica'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.presentation'),
        ),
    ]
