# Generated by Django 4.1 on 2023-01-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0006_billedincome_customer_company_creation_company_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='imagen',
            field=models.ImageField(default='../assets/images/users/no_photo.jpeg', null=True, upload_to='customers/', verbose_name='Foto de perfil'),
        ),
    ]
