# Generated by Django 4.1 on 2023-01-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0007_alter_customer_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='imagen',
            field=models.ImageField(default='customers/NoPhoto.png', null=True, upload_to='customers/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='imagen',
            field=models.ImageField(default='employees/NoPhoto.png', null=True, upload_to='employees/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='imagen',
            field=models.ImageField(blank=True, default='units/NoPhoto.png', null=True, upload_to='units/', verbose_name='Foto'),
        ),
    ]
