# Generated by Django 4.1 on 2023-01-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0008_alter_customer_imagen_alter_employee_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsPaidPlugins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.IntegerField(null=True, verbose_name='Factura')),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Codigo')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaidPlugins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.CharField(max_length=200, null=True, verbose_name='Folio')),
                ('payment_date', models.DateField(max_length=50, null=True, verbose_name='Fecha de pago')),
                ('date_issue', models.DateField(max_length=50, null=True, verbose_name='Fecha de emision')),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Codigo')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('account', models.ManyToManyField(blank=True, to='systemERP.bankaccount')),
                ('bills', models.ManyToManyField(blank=True, to='systemERP.billspaidplugins')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.company')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
