# Generated by Django 4.1 on 2023-01-29 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0009_billspaidplugins_paidplugins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidplugins',
            name='account',
        ),
        migrations.AddField(
            model_name='paidplugins',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bankaccount'),
        ),
    ]
