# Generated by Django 4.1 on 2023-01-29 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0010_remove_paidplugins_account_paidplugins_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billspaidplugins',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer', verbose_name='Cliente'),
        ),
    ]
