# Generated by Django 4.1 on 2023-01-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0012_customer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountsEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.BigIntegerField(unique=True, verbose_name='Número de cuenta')),
                ('interbank_key', models.BigIntegerField(unique=True, verbose_name='Clave interbancaria')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bank', verbose_name='Banco')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
