# Generated by Django 4.1 on 2023-01-31 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0013_bankaccountsemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='inputs',
        ),
        migrations.AddField(
            model_name='user',
            name='BillOfLading',
            field=models.BooleanField(null=True, verbose_name='Carta porte'),
        ),
        migrations.AddField(
            model_name='user',
            name='BilledIncome',
            field=models.BooleanField(null=True, verbose_name='Ingresos Facturados'),
        ),
        migrations.AddField(
            model_name='user',
            name='CreditNotes',
            field=models.BooleanField(null=True, verbose_name='Notas de credito'),
        ),
        migrations.AddField(
            model_name='user',
            name='DepositControl',
            field=models.BooleanField(null=True, verbose_name='Control de depositos'),
        ),
        migrations.AddField(
            model_name='user',
            name='DoubleDays',
            field=models.BooleanField(null=True, verbose_name='Dias dobles'),
        ),
        migrations.AddField(
            model_name='user',
            name='ExtraHours',
            field=models.BooleanField(null=True, verbose_name='Horas extras'),
        ),
        migrations.AddField(
            model_name='user',
            name='LandRent',
            field=models.BooleanField(null=True, verbose_name='Reta de tierras'),
        ),
        migrations.AddField(
            model_name='user',
            name='PaidPlugins',
            field=models.BooleanField(null=True, verbose_name='Complementos de pago'),
        ),
        migrations.AddField(
            model_name='user',
            name='PaymentOrderProducer',
            field=models.BooleanField(null=True, verbose_name='Orden de pago'),
        ),
        migrations.AddField(
            model_name='user',
            name='PaymentSchedule',
            field=models.BooleanField(null=True, verbose_name='Programación de pagos'),
        ),
        migrations.AddField(
            model_name='user',
            name='PettyCash',
            field=models.BooleanField(null=True, verbose_name='Caja chica'),
        ),
        migrations.AddField(
            model_name='user',
            name='chargers',
            field=models.BooleanField(null=True, verbose_name='Sueldo cargadores'),
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.BooleanField(null=True, verbose_name='compañias'),
        ),
        migrations.AddField(
            model_name='user',
            name='drivers',
            field=models.BooleanField(null=True, verbose_name='Sueldo choferes'),
        ),
        migrations.AddField(
            model_name='user',
            name='loans',
            field=models.BooleanField(null=True, verbose_name='prestamos'),
        ),
        migrations.AddField(
            model_name='user',
            name='payments',
            field=models.BooleanField(null=True, verbose_name='Pagos'),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll',
            field=models.BooleanField(null=True, verbose_name='Nomina'),
        ),
        migrations.AddField(
            model_name='user',
            name='props',
            field=models.BooleanField(null=True, verbose_name='Apoyos'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankUser', to='systemERP.user'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LoansUser', to='systemERP.user'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PayrollUser', to='systemERP.user'),
        ),
        migrations.AlterField(
            model_name='props',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PropsUser', to='systemERP.user'),
        ),
    ]
