# Generated by Django 4.1 on 2023-02-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0014_remove_user_inputs_user_billoflading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountsProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.BigIntegerField(unique=True, verbose_name='Número de cuenta')),
                ('interbank_key', models.BigIntegerField(unique=True, verbose_name='Clave interbancaria')),
                ('owner', models.CharField(max_length=500, null=True, verbose_name='Propietario')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bank', verbose_name='Banco')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
