# Generated by Django 4.1 on 2023-02-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0015_bankaccountsprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.IntegerField(null=True, verbose_name='No. de Factura'),
        ),
    ]
