# Generated by Django 4.1 on 2023-02-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0017_alter_productquotation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcn',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemERP.product'),
        ),
    ]
