# Generated by Django 4.1 on 2023-02-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0018_alter_productcn_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsDrivers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Pago')),
                ('comment', models.CharField(max_length=500, null=True, verbose_name='Comentario')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsChargers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Pago')),
                ('comment', models.CharField(max_length=500, null=True, verbose_name='Comentario')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
