# Generated by Django 4.1 on 2023-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0019_paymentsdrivers_paymentschargers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='discount',
            field=models.BooleanField(null=True, verbose_name='Descuento'),
        ),
    ]
