# Generated by Django 4.1 on 2023-02-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0020_pettycash_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputproduct',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.product'),
        ),
    ]
