# Generated by Django 4.1 on 2023-02-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0021_alter_outputproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='BillOfLading',
            field=models.BooleanField(default=False, null=True, verbose_name='Carta porte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='BilledIncome',
            field=models.BooleanField(default=False, null=True, verbose_name='Ingresos Facturados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreditNotes',
            field=models.BooleanField(default=False, null=True, verbose_name='Notas de credito'),
        ),
        migrations.AlterField(
            model_name='user',
            name='DepositControl',
            field=models.BooleanField(default=False, null=True, verbose_name='Control de depositos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='DoubleDays',
            field=models.BooleanField(default=False, null=True, verbose_name='Dias dobles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ExtraHours',
            field=models.BooleanField(default=False, null=True, verbose_name='Horas extras'),
        ),
        migrations.AlterField(
            model_name='user',
            name='LandRent',
            field=models.BooleanField(default=False, null=True, verbose_name='Reta de tierras'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PaidPlugins',
            field=models.BooleanField(default=False, null=True, verbose_name='Complementos de pago'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PaymentOrderProducer',
            field=models.BooleanField(default=False, null=True, verbose_name='Orden de pago'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PaymentSchedule',
            field=models.BooleanField(default=False, null=True, verbose_name='Programación de pagos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PettyCash',
            field=models.BooleanField(default=False, null=True, verbose_name='Caja chica'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banks',
            field=models.BooleanField(default=False, null=True, verbose_name='bancos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='binnacle',
            field=models.BooleanField(default=False, null=True, verbose_name='bitacora'),
        ),
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.BooleanField(default=False, null=True, verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chargers',
            field=models.BooleanField(default=False, null=True, verbose_name='Sueldo cargadores'),
        ),
        migrations.AlterField(
            model_name='user',
            name='companies',
            field=models.BooleanField(default=False, null=True, verbose_name='compañias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='customers',
            field=models.BooleanField(default=False, null=True, verbose_name='clientes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete',
            field=models.BooleanField(default=False, null=True, verbose_name='Eliminar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departments',
            field=models.BooleanField(default=False, null=True, verbose_name='departamentos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='drivers',
            field=models.BooleanField(default=False, null=True, verbose_name='Sueldo choferes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='edit',
            field=models.BooleanField(default=False, null=True, verbose_name='Editar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employees',
            field=models.BooleanField(default=False, null=True, verbose_name='empleados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='export',
            field=models.BooleanField(default=False, null=True, verbose_name='Exportar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fuels',
            field=models.BooleanField(default=False, null=True, verbose_name='combustible'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loans',
            field=models.BooleanField(default=False, null=True, verbose_name='prestamos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='outputs',
            field=models.BooleanField(default=False, null=True, verbose_name='salidas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parcels',
            field=models.BooleanField(default=False, null=True, verbose_name='parcelas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payments',
            field=models.BooleanField(default=False, null=True, verbose_name='Pagos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payroll',
            field=models.BooleanField(default=False, null=True, verbose_name='Nomina'),
        ),
        migrations.AlterField(
            model_name='user',
            name='producers',
            field=models.BooleanField(default=False, null=True, verbose_name='productores'),
        ),
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.BooleanField(default=False, null=True, verbose_name='productos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='props',
            field=models.BooleanField(default=False, null=True, verbose_name='Apoyos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='providers',
            field=models.BooleanField(default=False, null=True, verbose_name='proveedores'),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchase_orders',
            field=models.BooleanField(default=False, null=True, verbose_name='orden de venta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='quotes',
            field=models.BooleanField(default=False, null=True, verbose_name='cotizaciones'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reception',
            field=models.BooleanField(default=False, null=True, verbose_name='reception'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requisitions',
            field=models.BooleanField(default=False, null=True, verbose_name='requisiciones'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shoppings',
            field=models.BooleanField(default=False, null=True, verbose_name='compras'),
        ),
        migrations.AlterField(
            model_name='user',
            name='societies',
            field=models.BooleanField(default=False, null=True, verbose_name='sociedades'),
        ),
        migrations.AlterField(
            model_name='user',
            name='units',
            field=models.BooleanField(default=False, null=True, verbose_name='unidades'),
        ),
        migrations.AlterField(
            model_name='user',
            name='users',
            field=models.BooleanField(default=False, null=True, verbose_name='usuarios'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watch',
            field=models.BooleanField(default=False, null=True, verbose_name='Visualizar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='write',
            field=models.BooleanField(default=False, null=True, verbose_name='Escribir'),
        ),
    ]
