# Generated by Django 4.1 on 2023-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0022_alter_user_billoflading_alter_user_billedincome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='C_VerificationNo',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Numeor de verificacion contaminantes'),
        ),
        migrations.AddField(
            model_name='unit',
            name='PM_VerificationNo',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Numero de verificacion fisicomecanico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rfc',
            field=models.CharField(max_length=50, verbose_name='RFC'),
        ),
    ]
