# Generated by Django 4.1 on 2023-02-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0025_remove_fueling_km_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.fueltype'),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.unit'),
        ),
    ]
