# Generated by Django 4.1 on 2023-02-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0026_alter_fueling_fuel_type_alter_fueling_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueling',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Capacidad de combustible'),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='liters',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Litros'),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Kilometraje'),
        ),
    ]
