# Generated by Django 4.1 on 2023-02-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0027_fueling_fuel_capacity_alter_fueling_liters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelDump',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, verbose_name='Fecha')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=19, null=True, verbose_name='Capacidad')),
                ('current_conten', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=19, null=True, verbose_name='Capacidad')),
                ('liters_discharged', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=19, null=True, verbose_name='Capacidad')),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Comentario')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.fueltype')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.unit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
