# Generated by Django 4.1 on 2023-02-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0028_fueldump'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueldump',
            old_name='current_conten',
            new_name='current_content',
        ),
    ]
