# Generated by Django 4.1 on 2023-02-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0029_rename_current_conten_fueldump_current_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=50, null=True, verbose_name='Unidad')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Precio')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Subtotal')),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Codigo')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemERP.presentation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemERP.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('purchase_order', models.IntegerField(null=True, verbose_name='Orden de pedido')),
                ('date_delivery', models.DateField(max_length=50, null=True, verbose_name='Fecha de entrega')),
                ('order_number', models.IntegerField(null=True, verbose_name='Orden de pedido')),
                ('place_delivery', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Lugar de entrega')),
                ('sale_condition', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Condición de venta')),
                ('invoice', models.IntegerField(null=True, verbose_name='No. de Factura')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Iva')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Subtotal')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Total')),
                ('observation', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Observación')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('auxiliary_sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POauxiliary', to='systemERP.employee', verbose_name='Auxiliar de ventas')),
                ('business_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer')),
                ('creditnote_products', models.ManyToManyField(blank=True, to='systemERP.productpo')),
                ('qa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POQA', to='systemERP.employee', verbose_name='Control de calidad')),
                ('storekeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POstorekeeper', to='systemERP.employee', verbose_name='Almacenista')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
