# Generated by Django 4.1 on 2023-02-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0030_productpo_purchaseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='creditnote_products',
            new_name='POproducts',
        ),
    ]
