# Generated by Django 4.1 on 2023-02-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0031_rename_creditnote_products_purchaseorder_poproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binnacle',
            name='lotes',
            field=models.CharField(max_length=500, null=True, verbose_name='Lotes'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('second_surname', models.CharField(max_length=100, null=True, verbose_name='Apellido Materno')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('second_surname', models.CharField(max_length=100, null=True, verbose_name='Apellido Materno')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
