# Generated by Django 4.1 on 2023-02-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0032_alter_binnacle_lotes_driver_charger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='no_parcel',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Número de parcela'),
        ),
    ]
