# Generated by Django 4.1 on 2023-02-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0033_alter_parcel_no_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segalmexreception',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='Localidad'),
        ),
    ]
