# Generated by Django 4.1 on 2023-02-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0034_alter_segalmexreception_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='segalmexreception',
            name='company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.company', verbose_name='Compañia'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='period',
            field=models.CharField(max_length=100, null=True, verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
    ]
