# Generated by Django 4.1 on 2023-02-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0035_segalmexreception_company_segalmexreception_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segalmexreception',
            name='cr_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='cuticula roja y dictaminado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='cr_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='cuticula roja y deduccion aplicable'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='cr_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='cuticula roja y tolerancia'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='ge_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano estrellado y dictaminado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='ge_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano estrellado y deduccion aplicable'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='ge_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano estrellado y tolerancia'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gm_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano manchado y dictaminado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gm_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano manchado y deduccion aplicable'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gm_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano manchado y tolerancia'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gq_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano quebrado y dictaminado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gq_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano quebrado y deduccion aplicable'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gq_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano quebrado y tolerancia'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gv_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano verde y dictaminado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gv_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano verde y deduccion aplicable'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='gv_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='grano verde y tolerancia'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='h_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='humedad y dictaminado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='h_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='humedad y deduccion aplicable'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='h_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='humedad y tolerancia'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='i_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='impurezas y dictaminado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='i_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='impurezas y deduccion aplicable'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='i_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='impurezas y tolerancia'),
        ),
    ]
