# Generated by Django 4.1 on 2023-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0036_segalmexreception_cr_d_segalmexreception_cr_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segalmexreception',
            name='action',
            field=models.CharField(max_length=50, null=True, verbose_name='accion'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Saldo a liquidar'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='balance_letters',
            field=models.CharField(max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='contract',
            field=models.CharField(max_length=100, null=True, verbose_name='contrato'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='municipality',
            field=models.CharField(max_length=100, null=True, verbose_name='municipio'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='net_analyzed',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Neto analizado'),
        ),
        migrations.AddField(
            model_name='segalmexreception',
            name='observation',
            field=models.CharField(max_length=500, null=True, verbose_name='Observacion'),
        ),
    ]
