# Generated by Django 4.1 on 2023-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0037_segalmexreception_action_segalmexreception_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialCash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Importe')),
            ],
        ),
    ]
