# Generated by Django 4.1 on 2023-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0038_initialcash'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_admission',
            field=models.DateField(null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sr',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Estatura'),
        ),
    ]
