# Generated by Django 4.1 on 2023-03-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0039_employee_date_admission_employee_sr'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='status',
            field=models.CharField(max_length=500, null=True, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Abono')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.loans', verbose_name='Prestamo')),
            ],
        ),
    ]
