# Generated by Django 4.1 on 2023-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0040_loans_status_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputproduct',
            name='no',
            field=models.IntegerField(default=0, null=True, verbose_name='No'),
        ),
    ]
