# Generated by Django 4.1 on 2023-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0041_outputproduct_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
