# Generated by Django 4.1 on 2023-03-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0042_alter_outputproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='systemERP.employee'),
        ),
    ]
