# Generated by Django 4.1 on 2023-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0043_alter_loans_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Prestamo'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Abonos'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Abono'),
        ),
    ]
