# Generated by Django 4.1 on 2023-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0044_alter_loans_loan_alter_loans_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='hours_worked',
            field=models.IntegerField(null=True, verbose_name='Horas trabajadas'),
        ),
    ]
