# Generated by Django 4.1 on 2023-03-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0046_payroll_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conciliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('reference', models.CharField(max_length=200, null=True, verbose_name='Referencia bancaria')),
                ('beneficiary', models.CharField(max_length=500, null=True, verbose_name='Beneficiario')),
                ('concept', models.CharField(max_length=200, null=True, verbose_name='Concepto')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Deposito')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Cargo')),
                ('pending_charge', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Cargo Pendiente')),
                ('countable_balance', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Saldo Contable')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Saldo Bancario')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bankaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
