# Generated by Django 4.1 on 2023-03-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0047_conciliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='POproducts',
            new_name='products',
        ),
    ]
