# Generated by Django 4.1 on 2023-03-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0048_rename_poproducts_purchaseorder_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPresentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, unique=True, verbose_name='Presentation')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('deadline', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('due_date', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Peso neto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Precio unitario')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Importe')),
                ('status', models.CharField(max_length=500, null=True, verbose_name='Estado')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer')),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.mainpresentation')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.mainproduct')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.purchaseorder')),
            ],
        ),
    ]
