# Generated by Django 4.1 on 2023-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0049_mainpresentation_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='sale',
            name='deadline',
            field=models.DateField(max_length=50, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
