# Generated by Django 4.1 on 2023-03-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0050_remove_sale_due_date_alter_sale_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.presentation'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.product'),
        ),
    ]
