# Generated by Django 4.1 on 2023-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0051_alter_sale_presentation_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='purchase_order',
            field=models.IntegerField(null=True, verbose_name='Orden de pedido'),
        ),
    ]
