# Generated by Django 4.1 on 2023-04-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0052_alter_sale_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user'),
        ),
    ]
