# Generated by Django 4.1 on 2023-04-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0053_sale_creation_sale_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billedincome',
            name='amount_receivable',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='bank_deposits',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='bills_paid',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='company',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='credit_note',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='status',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='unit_price',
        ),
    ]
