# Generated by Django 4.1 on 2023-04-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0054_remove_billedincome_amount_receivable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.IntegerField(null=True, verbose_name='Factura')),
                ('credit_note', models.IntegerField(null=True, verbose_name='Nota de credito')),
                ('payment_plugin', models.IntegerField(null=True, verbose_name='Complemento de pago')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.bankaccount')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
