# Generated by Django 4.1 on 2023-04-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0055_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='credit_note',
        ),
        migrations.RemoveField(
            model_name='income',
            name='invoice',
        ),
        migrations.CreateModel(
            name='IncomeCreditNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creditnote', models.IntegerField(null=True, verbose_name='Notas de credito')),
                ('income', models.IntegerField(null=True, verbose_name='Income')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeBills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.IntegerField(null=True, verbose_name='Factura')),
                ('income', models.IntegerField(null=True, verbose_name='Income')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='creditnotes',
            field=models.ManyToManyField(blank=True, related_name='notas', to='systemERP.incomecreditnotes'),
        ),
        migrations.AddField(
            model_name='income',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='facturas', to='systemERP.incomebills'),
        ),
    ]
