# Generated by Django 4.1 on 2023-04-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0057_rename_incomebills_incomeinvoices_income_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeinvoices',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.billedincome'),
        ),
    ]
