# Generated by Django 4.1 on 2023-04-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0058_alter_incomeinvoices_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='attention',
            field=models.CharField(max_length=500, null=True, verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='incomecreditnotes',
            name='creditnote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.creditnote'),
        ),
    ]
