# Generated by Django 4.1 on 2023-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0059_quotation_attention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Iva'),
        ),
        migrations.AlterField(
            model_name='output',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='output',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Total'),
        ),
    ]
