# Generated by Django 4.1 on 2023-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0060_alter_output_iva_alter_output_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Subtotal'),
        ),
    ]
