# Generated by Django 4.1 on 2023-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0061_alter_output_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='attention',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Atención'),
        ),
    ]
