# Generated by Django 4.1 on 2023-04-26 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0062_alter_quotation_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billspaidplugins',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.billedincome', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_plugin',
            field=models.CharField(max_length=100, null=True, verbose_name='Complemento de pago'),
        ),
    ]
