# Generated by Django 4.1 on 2023-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0063_alter_billspaidplugins_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidplugins',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Importe'),
        ),
    ]
