# Generated by Django 4.1 on 2023-04-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0064_paidplugins_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='status'),
        ),
    ]
