# Generated by Django 4.1 on 2023-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0065_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrent',
            name='comment',
            field=models.CharField(max_length=200, null=True, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='bank_account',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cuenta bancaria'),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='parcel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Parcelas'),
        ),
    ]
