# Generated by Django 4.1 on 2023-05-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0066_landrent_comment_alter_landrent_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrent',
            name='hectares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Superficie'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='lessor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='price_hectare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Precio por hectarea'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='rental_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor de renta'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='Metodo de pago'),
        ),
    ]
