# Generated by Django 4.1 on 2023-05-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0067_landrent_hectares_landrent_lessor_landrent_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyProducers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.producer')),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.society')),
            ],
        ),
    ]
