# Generated by Django 4.1 on 2023-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0068_societyproducers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueling',
            name='last_hours',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Ultimas Horas Trabajadas'),
        ),
        migrations.AddField(
            model_name='unit',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Horas Trabajadas'),
        ),
        migrations.AlterField(
            model_name='fueling',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Horas Trabajadas'),
        ),
    ]
