# Generated by Django 4.1 on 2023-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0070_fueling_liters_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueling',
            name='liters_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=19, null=True, verbose_name='Litros/Horas'),
        ),
    ]
