# Generated by Django 4.1 on 2023-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0071_alter_fueling_liters_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.0', max_digits=19, null=True, verbose_name='Horas Trabajadas'),
        ),
    ]
