# Generated by Django 4.1 on 2023-05-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0072_alter_unit_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Conciliation',
            field=models.BooleanField(default=False, null=True, verbose_name='Conciliaciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='Income',
            field=models.BooleanField(default=False, null=True, verbose_name='Ingresos'),
        ),
    ]
