# Generated by Django 4.1 on 2023-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0073_user_conciliation_user_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedincome',
            name='due_date',
            field=models.DateField(max_length=50, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
