# Generated by Django 4.1 on 2023-05-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0074_billedincome_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billedincome',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductBilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Peso neto')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Precio')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Subtotal')),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.presentation')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.product')),
            ],
        ),
        migrations.AddField(
            model_name='billedincome',
            name='products',
            field=models.ManyToManyField(blank=True, to='systemERP.productbilled'),
        ),
    ]
