# Generated by Django 4.1 on 2023-05-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0075_remove_billedincome_product_productbilled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billedincome',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='billedincome',
            name='net_weight',
        ),
        migrations.AddField(
            model_name='billedincome',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='tootal'),
        ),
    ]
