# Generated by Django 4.1 on 2023-05-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0076_remove_billedincome_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBilled',
            new_name='ProductBI',
        ),
        migrations.RenameField(
            model_name='creditnote',
            old_name='business_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='creditnote',
            old_name='creditnote_products',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.billedincome'),
        ),
    ]
