# Generated by Django 4.1 on 2023-05-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0078_creditnote_no_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='voucher',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Comprobante'),
        ),
    ]
