# Generated by Django 4.1 on 2023-05-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0079_purchaseorder_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbi',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='productbi',
            name='unit',
            field=models.CharField(max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
