# Generated by Django 4.1 on 2023-05-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0081_paidplugins_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.paidplugins'),
        ),
    ]
