# Generated by Django 4.1 on 2023-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0082_alter_income_payment_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='billedincome',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='billedincome',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='total'),
        ),
    ]
