# Generated by Django 4.1 on 2023-05-27 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0083_billedincome_net_weight_alter_billedincome_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargersalary',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chargersalary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user'),
        ),
    ]
