# Generated by Django 4.1 on 2023-05-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0084_chargersalary_creation_chargersalary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segalmexreception',
            name='action',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='accion'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Saldo a liquidar'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='balance_letters',
            field=models.CharField(default=0, max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='checkin_date',
            field=models.DateField(default='', max_length=50, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='checkin_time',
            field=models.TimeField(default='', max_length=50, null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='checkout_date',
            field=models.DateField(default='', max_length=50, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='checkout_time',
            field=models.TimeField(default='', max_length=50, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='comment',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='contract',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='contrato'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='discounted_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Peso con descuento'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='driver',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chofer', to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='field_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Peso campo'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Flete'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Peso bruto'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='location',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='lot',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='municipality',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='net_analyzed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Neto analizado'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='observation',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='period',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='plate',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.unit', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='producer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.producer', verbose_name='Productor'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='receive',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recibio', to='systemERP.employee'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='tare_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Peso tara'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='ticket',
            field=models.IntegerField(default='', null=True, verbose_name='No. de Boleta'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='segalmexreception',
            name='variety',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.variety', verbose_name='variedad'),
        ),
    ]
