# Generated by Django 4.1 on 2023-06-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0091_alter_purchaseorder_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Silo')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
            ],
        ),
    ]
