# Generated by Django 4.1 on 2023-07-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0092_silo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, null=True, verbose_name='Fecha')),
                ('turn', models.CharField(max_length=500, null=True, verbose_name='Turno')),
                ('gr_5', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Granel_5')),
                ('gr_10', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Granel_10')),
                ('gr_15', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Granel_15')),
                ('gr_20', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Granel_20')),
                ('gr_25', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Granel_25')),
                ('env_5', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Envasado_5')),
                ('env_15', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Envasado_15')),
                ('env_20', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Envasado_20')),
                ('env_25', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Envasado_25')),
                ('rejection_5', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Rechazo_5')),
                ('stained_5', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Manchado_5')),
                ('half_grain', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Medio grano')),
                ('granule', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Granillo')),
                ('polished', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Pulido')),
                ('selgron', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Selgron')),
                ('peel', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Cascara')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Total')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('miller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='molinero', to='systemERP.employee', verbose_name='Molinero')),
                ('silo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.silo', verbose_name='Silo')),
                ('storer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacenista', to='systemERP.employee', verbose_name='Almacenista')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.user')),
                ('variety', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemERP.variety', verbose_name='Variedad')),
            ],
        ),
    ]
