# Generated by Django 4.1 on 2023-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemERP', '0093_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='observation',
            field=models.CharField(max_length=200, null=True, verbose_name='Observación'),
        ),
    ]
